The data in this notebook is sourced from:
     Kielland, K., F.S. Chapin, R.W. Ruess, and Bonanza Creek LTER. 2017. Snowshoe hare physical data in Bonanza Creek Experimental Forest: 1999-Present ver 22. Environmental Data Initiative. https://doi.org/10.6073/pasta/03dce4856d79b91557d8e6ce2cbcdc14 (Accessed 2026-10-16).

https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-bnz.55.22

The data was assembled by Kielland, Chapin, and Ruess, as well as the Bonanza Creek LTER. The purpose of the collection of the data was to study the snowshoe hare population over a period of time. 

A singular row represents one trapping of one snowshoe hare.

The observations were collected between 1999 and 2012, between Tok and Clear, Alaska. 

There is no sensitive data.

The study protocols included trapping the snowhares, as well as tagging the right and left ears. 

Weight is measured in grams. 

Missing data is encoded as a blank cell.

The associated publication is Kielland, K., F.S. Chapin, R.W. Ruess, and Bonanza Creek LTER. 2017. Snowshoe hare physical data in Bonanza Creek Experimental Forest: 1999-Present ver 22. Environmental Data Initiative. https://doi.org/10.6073/pasta/03dce4856d79b91557d8e6ce2cbcdc14 (Accessed 2026-10-16).


```python
![image description](https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg/1920px-SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail&_=20170313021652)
```

In [3]:
import pandas as pd

In [4]:
hares = pd.read_csv('data/55_Hare_Data_2012.txt')

In [5]:
hares.head()

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,11/26/1998,NaN,bonrip,1A,414D096A08,NaN,NaN,NaN,1370.0,160.0,NaN,917.0,51,Population
1,11/26/1998,NaN,bonrip,2C,414D320671,NaN,M,NaN,1430.0,NaN,NaN,936.0,51,Population
2,11/26/1998,NaN,bonrip,2D,414D103E3A,NaN,M,NaN,1430.0,NaN,NaN,921.0,51,Population
3,11/26/1998,NaN,bonrip,2E,414D262D43,NaN,NaN,NaN,1490.0,135.0,NaN,931.0,51,Population
4,11/26/1998,NaN,bonrip,3B,414D2B4B58,NaN,NaN,NaN,1710.0,150.0,NaN,933.0,51,Population

In [6]:
hares.shape

(3380, 14)

In [7]:
hares.isna()

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,False,True,False,False,False,True,True,True,False,False,True,False,False,False
1,False,True,False,False,False,True,False,True,False,True,True,False,False,False
2,False,True,False,False,False,True,False,True,False,True,True,False,False,False
3,False,True,False,False,False,True,True,True,False,False,True,False,False,False
4,False,True,False,False,False,True,True,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3375,False,False,False,False,False,False,True,True,False,True,True,False,False,False
3376,False,False,False,False,False,False,True,True,True,True,True,False,False,False
3377,False,True,False,False,False,False,True,True,False,False,True,False,False,False
3378,False,True,False,False,False,False,True,True,False,True,True,False,False,False
3379,False,True,False,False,False,False,False,True,False,False,True,False,False,False

In [16]:
hares['hindft'].max()
hares['hindft'].min()
hares['weight'].max()
hares['weight'].min()

0.0

In [17]:
hares.dtypes

date           object
time           object
grid           object
trap           object
l_ear          object
r_ear          object
sex            object
age            object
weight        float64
hindft        float64
notes          object
b_key         float64
session_id      int64
study          object
dtype: object

In [23]:
hares['grid'].unique()
hares['study'].unique()

array(['Population', 'Collar', nan, 'Metabolic', 'Metabolic/Collar'],
      dtype=object)